### ISSUE TITLE
Error on website

### ISSUE THREAD

**Issue by MumsOnGit** [samihan-m/youtube-video-dmca-checker-website#2]
"An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail"

**Comment by samihan-m** [comment]
Hey, I'm out of free Heroku hosting hours for the month. Once the monthly period refreshes it'll be back up :) Check back in a few days

**Comment by samihan-m** [comment]
I might move to replit soon because heroku is getting rid of their free hosting tier, so if you plan on using the site more definitely let me know and I can prioritize it more

**Comment by MumsOnGit** [comment]
Ah that stinks, but I suppose that comes with free hosting. I don't imagine you'd want any recommendations on (very) cheap Linux VMs since Heroku is already set up and all; in any case, my friends and I use this tool sparingly, so it's not a _big_ deal. Thanks for sharing something useful for free and for the quick response!

**Comment by samihan-m** [comment]
I'm glad the site is helpful for you guys. And hey, for sure forward me any information you want to share, I'm totally open to knowing more about deploying things. I totally might not use it for this case, but having the info would be cool!

**Comment by MumsOnGit** [comment]
I guess I haven't been on here in a while, I could have sworn we had DMs...anyway, check out BuyVM.net (formerly Frantech.ca). It's all in-house and they're good guys. Used them to host private game servers back in the day and they're still around and just as affordable as ever.

**Comment by samihan-m** [comment]
Super cool. Good to know! Thanks man, I'll definitely check it out
